SPECS: python-numpy: Upgrade to 2.4.6.
This also fixes x86-64 build error under gcc16 due to old
x86-simd-sort code, like:

[  241s]   ../numpy/_core/src/npysort/x86-simd-sort/src/xss-common-comparators.hpp:43:32: error: inlining failed in call to ‘always_inline’ ‘STDSortComparator’: target specific option mismatch
[  241s]      43 |     X86_SIMD_SORT_FINLINE bool STDSortComparator(const type_t &a,
[  241s]         |                                ^
[  241s]   /usr/include/c++/16/bits/stl_algo.h:1757:20: note: called from here
[  241s]    1757 |       while (__comp(__val, *__next))
[  241s]         |                    ^

Signed-off-by: Kai Zhang <zhangkai@iscas.ac.cn>